version: '3.9'

services:
  db:
    image: postgres
    restart: always
    container_name: jwt-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminPS
      POSTGRES_DB: userServiceDB
    volumes:
      - db_data:/var/lib/postgresql/datayour
    ports:
      - "5342:5432"

  app:
    depends_on:
      - db
    build: .
    restart: on-failure
    env_file: ./.env
    ports:
      - "8001:8080"
    volumes:
      - app:/root/.m2
    stdin_open:  true
    tty: true


volumes:
  db_data:
  app:
