version: '3.9'

services:
  db:
    image: postgres
    restart: always
    container_name: jwt-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminPS
      POSTGRES_DB: userServiceDB
    volumes:
      - db_data:/var/lib/postgresql/datayour
    ports:
      - "5342:5432"

volumes:
  db_data:
