version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    container_name: jwt-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}

  app:
    depends_on:
      - db
    build: .
    restart: on-failure
    env_file:
      - .env
    ports:
      - "8001:8080"
    volumes:
      - app:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db_data:
  app: