version: '3.9'

services:
  db:
    image: postgres
    restart: always
    container_name: jwt-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}

  app:
    depends_on:
      - db
    build: .
    restart: on-failure
    env_file:
      - .env
    environment:
      SPRING_APPLICATION_JSON: ' {
        "spring.datasource.url": "jdbc:postgresql://db:$POSTGRES_DOCKER_PORT/$POSTGRES_DB",
        "spring.datasource.username": "$POSTGRES_USER",
        "spring.datasource.password": "$POSTGRES_PASS",
        "spring.datasource.driver-class-name": "org.postgresql.Driver",
        "jwt.secret.key": "$JWT_SECRET_KEY",
        "spring.jpa.database-platform": "org.hibernate.dialect.PostgreSQLDialect",
        "spring.jpa.show-sql": true,
        "spring.jpa.hibernate.ddl-auto": "create"
        }'
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    volumes:
      - app:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db_data:
  app: